### ISSUE TITLE
generate_obj_graph() takes many hours to return

### ISSUE THREAD

**Issue by quisacrc** [Song-Li/ODGen#3]
Hi, 

Thanks for your amazingly useful open source. For recent few days, I have been trying to resolve an issue regarding using ODGen, but could not fix it.. I would really appreciate it if you could kindly help out on this. 

[This JS file (link)](https://drive.google.com/file/d/1cfVkbypbBhKkS0AcKBZg_Z2Pc4arPwse/view?usp=sharing) is what I have been trying to analyze by using ODGen. Basically, my goal is to do taint-tracking for some JavaScript variables in this JS file. So, I tried to generate an object dependency graph for this JS file and then create my own rule for taint-tracking. I ran the following command to generate an object dependency graph of the JS file:

`python ./odgen.py web-code.js --max-rep=1 -s -m -a -q -t os_command`

However, ODGen's `generate_obj_graph()` function takes several hours to return. Further, another interesting issue is that if I cut down the JS file's size and create a [smaller JS file (link)](https://drive.google.com/file/d/1bmJLKnKak_xLnD35q0ppcLgLUp85aSK8/view?usp=sharing) which contains only line 1~18387 of the original file (about 40% of the original file size), it takes only a few seconds to complete the whole execution of ODGen analysis. 

I wonder if you could please take a look at this issue to figure out why the `generate_obj_graph()` function is taking a too long time to complete, and much more importantly, how to make this function return much faster (losing analysis accuracy for a certain degree is ok, as far as the analysis becomes practically faster). 

I really appreciate your kind help in advance.

**Comment by Song-Li** [comment]
Hi,

Analyzing large JS programs is always the pain point of static analysis. I believe you have already picked the fastest way to test your file. For very large JS files (like your file), the path- and context-sensitive static analysis tools are very likely to 
encounter the efficiency problem. 

At the same time, our team is implementing a new strategy, which designs for large JS packages and can significantly increase the running speed of static analysis. Unfortunately, this implementation is not ready for release now. Once the paper is finished, we will release our new approach!

Thank you!
